//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagmentSystemFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_LOANS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK_LOANS()
        {
            this.FINES = new HashSet<FINE>();
        }
    
        public int LOAN_ID { get; set; }
        public Nullable<long> ISBN { get; set; }
        public Nullable<int> CARD_ID { get; set; }
        public System.DateTime DATE_OUT { get; set; }
        public System.DateTime DUE_DATE { get; set; }
        public Nullable<System.DateTime> DATE_IN { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual BORROWER BORROWER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINE> FINES { get; set; }
    }
}
