//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagmentSystemFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_AUTHORS
    {
        public Nullable<int> AUTHOR_ID { get; set; }
        public long ISBN { get; set; }
    
        public virtual AUTHOR AUTHOR { get; set; }
        public virtual BOOK BOOK { get; set; }
    }
}
