//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagmentSystemFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LIbraryManagementDBContext : DbContext
    {
        public LIbraryManagementDBContext()
            : base("name=LIbraryManagementDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHOR> AUTHORS { get; set; }
        public virtual DbSet<BOOK> BOOKs { get; set; }
        public virtual DbSet<BOOK_LOANS> BOOK_LOANS { get; set; }
        public virtual DbSet<BORROWER> BORROWERs { get; set; }
        public virtual DbSet<BOOK_AUTHORS> BOOK_AUTHORS { get; set; }
        public virtual DbSet<FINE> FINES { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
        public virtual DbSet<SearchNew> SearchNews { get; set; }
        public virtual DbSet<vWSEARCH> vWSEARCHes { get; set; }
    }
}
